# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20161111_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='stats',
            new_name='slots',
        ),
    ]
