# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20161111_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
