# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_subject_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='units',
            field=models.IntegerField(default=3),
        ),
    ]
